language: python
cache: pip
python:
  - 2.6
  - 2.7
  - pypy
  - 3.2
  - 3.3
  - 3.4
  - pypy3
install:
  - pip install azure
  - pip install coveralls
  - pip install pytest-cov
  - pip install requests
  - pip install requests_mock
env:
  - TEST_DIR=Python/Storage
script:
  - cd $TEST_DIR && PYTHONPATH=. py.test --cov-config ../.coveragerc --cov-report term-missing --cov blobxfer test/test_blobxfer.py
after_success:
  - coveralls --rcfile=../.coveragerc --verbose

